[project]
name = "logillm"
version = "0.1.0"
description = "logillm - project for college course Intro to AI course"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ruff>=0.15.20",
]

[project.scripts]
logillm = "logillm.cli:main"

[tool.uv]
package = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
# E,F = pycodestyle/pyflakes (osnovne greške)
# I   = sortiranje importova
# UP  = pyupgrade (moderniji sintaksni oblici)
# B   = flake8-bugbear (česte logičke zamke)